import {
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  Award,
  Beef,
  BedDouble,
  Bike,
  Bitcoin,
  Book,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  Car,
  Castle,
  CheckCircle2,
  ChevronDown,
  Clock,
  Code,
  Coins,
  Computer,
  CreditCard,
  Crown,
  Diamond,
  DollarSign,
  Euro,
  File,
  FileText,
  Flag,
  Gavel,
  Globe,
  Globe2,
  GraduationCap,
  HandCoins,
  Heart,
  Home,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  LineChart,
  Lock,
  Menu,
  Mic,
  Newspaper,
  Package,
  Palmtree,
  Phone,
  PieChart,
  PiggyBank,
  Plane,
  Play,
  PlayCircle,
  Puzzle,
  Receipt,
  Rocket,
  RotateCw,
  Scale,
  Search,
  Shield,
  ShieldCheck,
  Speech,
  Star,
  Target,
  Trees,
  TrendingUp,
  Umbrella,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  Wrench,
  X,
} from "lucide-react"

// Solutions Fiscales
export const solutionsFiscales = [
  // Défiscalisation Immobilière
  {
    id: "solution-1",
    title: "Déficit Foncier",
    description: "10 700€/an déductibles • Travaux rentabilisés",
    href: "/defiscalisation/deficit-foncier",
    icon: Wrench,
    isTitle: false,
  },
  {
    id: "solution-2",
    title: "Denormandie",
    description: "21% réduction IR • Rénovation énergétique",
    href: "/defiscalisation/denormandie",
    icon: Leaf,
    isTitle: false,
  },
  {
    id: "solution-3",
    title: "Passer en LMNP / LMP",
    description: "Zéro impôt 10-20 ans • Location meublée",
    href: "/defiscalisation/lmnp-lmp",
    icon: BedDouble,
    isTitle: false,
  },
  {
    id: "solution-4",
    title: "Loi Malraux",
    description: "30% réduction IR • Patrimoine historique",
    href: "/defiscalisation/malraux",
    icon: Castle,
    isTitle: false,
  },
  {
    id: "solution-5",
    title: "Monument Historique",
    description: "100% travaux déductibles • Zéro plafond",
    href: "/defiscalisation/monument-historique",
    icon: Building,
    isTitle: false,
  },
  // Défiscalisation Financière
  {
    id: "solution-6",
    title: "Girardin Industriel",
    description: "120% réduction • One-shot Outre-mer",
    href: "/defiscalisation/girardin",
    icon: Palmtree,
    isTitle: false,
  },
  {
    id: "solution-7",
    title: "PER",
    description: "100% déductible • Retraite + capital",
    href: "/defiscalisation/per",
    icon: PiggyBank,
    isTitle: false,
  },
  {
    id: "solution-8",
    title: "Groupements Forestiers",
    description: "25% IR + 75% IFI • Forêts & transmission",
    href: "/defiscalisation/groupements-forestiers",
    icon: Trees,
    isTitle: false,
  },
  {
    id: "solution-9",
    title: "FCPI",
    description: "25% réduction • Start-ups innovantes",
    href: "/defiscalisation/fcpi",
    icon: Lightbulb,
    isTitle: false,
  },
  {
    id: "solution-10",
    title: "Cheptel Bovin",
    description: "100% déductible • Rendement 5-7% an",
    href: "/defiscalisation/cheptel-bovin",
    icon: Beef,
    isTitle: false,
  },
];

// Placements
export const placementsCategories = [
  {
    title: "Supports d'investissement",
    products: [
      {
        id: "product-1",
        title: "Assurance-vie",
        description: "Support privilégié d'épargne",
        href: "/placements/assurance-vie",
        icon: Shield,
      },
      {
        id: "product-2",
        title: "Assurance-vie Luxembourgeoise",
        description: "Haut de gamme international",
        href: "/placements/assurance-vie-luxembourgeoise",
        icon: Crown,
      },
      {
        id: "product-3",
        title: "Contrat de capitalisation",
        description: "Transmission optimisée",
        href: "/placements/contrat-capitalisation",
        icon: Coins,
      },
      {
        id: "product-4",
        title: "PER",
        description: "Plan Épargne Retraite",
        href: "/placements/per",
        icon: RotateCw,
      },
      {
        id: "product-5",
        title: "PEA",
        description: "Actions européennes défiscalisées",
        href: "/placements/pea",
        icon: LineChart,
      },
      {
        id: "product-6",
        title: "Compte-Titres",
        description: "Investissement libre",
        href: "/placements/compte-titres",
        icon: Briefcase,
      },
    ],
  },
  {
    title: "Produits d'investissement",
    products: [
      {
        id: "product-7",
        title: "Private Equity",
        description: "Investissement non coté",
        href: "/placements/private-equity",
        icon: Diamond,
      },
      {
        id: "product-8",
        title: "Venture Capital",
        description: "Capital-risque innovant",
        href: "/placements/venture-capital",
        icon: TrendingUp,
      },
      {
        id: "product-9",
        title: "ETF",
        description: "Fonds indiciels cotés",
        href: "/placements/etf",
        icon: LineChart,
      },
      {
        id: "product-10",
        title: "Actions",
        description: "Titres de sociétés",
        href: "/placements/actions",
        icon: TrendingUp,
      },
      {
        id: "product-11",
        title: "Obligations",
        description: "Titres de créance",
        href: "/placements/obligations",
        icon: FileText,
      },
      {
        id: "product-12",
        title: "SCPI / OPCI",
        description: "Pierre-papier",
        href: "/placements/scpi-opci",
        icon: Building2,
      },
      {
        id: "product-13",
        title: "Cryptomonnaies",
        description: "Actifs digitaux",
        href: "/placements/crypto",
        icon: Bitcoin,
      },
      {
        id: "product-14",
        title: "Produits structurés",
        description: "Protection du capital",
        href: "/placements/produits-structures",
        icon: Shield,
      },
      {
        id: "product-15",
        title: "Métaux Précieux",
        description: "Or, Argent, Platine",
        href: "/placements/metaux-precieux",
        icon: Crown,
      },
      {
        id: "product-16",
        title: "Matières premières",
        description: "Commodités",
        href: "/placements/matieres-premieres",
        icon: Globe,
      },
    ],
  },
];

// Investissements
export const investissements = [
  // Immobilier
  {
    id: "invest-1",
    title: "Hagnéré Investissement",
    description: "Notre solution exclusive",
    href: "/investissements/hagnere-investissement",
    icon: Award,
    category: "immobilier",
  },
  {
    id: "invest-2",
    title: "SCPI Européenne",
    description: "Immobilier européen diversifié",
    href: "/investissements/scpi-europeenne",
    icon: Building,
    category: "immobilier",
  },
  {
    id: "invest-3",
    title: "Nue-Propriété",
    description: "Décote de 20 à 40%",
    href: "/investissements/nue-propriete",
    icon: Key,
    category: "immobilier",
  },
  {
    id: "invest-4",
    title: "Viager",
    description: "Investissement éthique",
    href: "/investissements/viager",
    icon: Users,
    category: "immobilier",
  },
  // Financier
  {
    id: "invest-5",
    title: "Groupements Forestiers",
    description: "Réduction IFI",
    href: "/investissements/groupements-forestiers",
    icon: Trees,
    category: "financier",
  },
  {
    id: "invest-6",
    title: "Cheptel Bovin",
    description: "Investissement agricole",
    href: "/investissements/cheptel-bovin",
    icon: Beef,
    category: "financier",
  },
];

// Financements
export const financements = [
  // Crédits immobiliers
  {
    id: "finance-1",
    title: "Prêt immobilier RP",
    description: "Résidence principale",
    href: "/financements/pret-immobilier-rp",
    icon: Home,
    category: "immobilier",
  },
  {
    id: "finance-2",
    title: "Prêt immobilier RS",
    description: "Résidence secondaire",
    href: "/financements/pret-immobilier-rs",
    icon: Home,
    category: "immobilier",
  },
  {
    id: "finance-3",
    title: "Prêt immobilier locatif",
    description: "Bien destiné à la location",
    href: "/financements/pret-immobilier-locatif",
    icon: Key,
    category: "immobilier",
  },
  {
    id: "finance-4",
    title: "Prêt relais",
    description: "Avance en attendant la vente",
    href: "/financements/pret-relais",
    icon: RotateCw,
    category: "immobilier",
  },
  {
    id: "finance-5",
    title: "Prêt in fine",
    description: "Capital remboursé à la fin",
    href: "/financements/pret-in-fine",
    icon: TrendingUp,
    category: "immobilier",
  },
  // Crédits spécialisés
  {
    id: "finance-6",
    title: "Crédit marchand de biens",
    description: "Achat, rénover, revendre",
    href: "/financements/credit-marchand",
    icon: Wrench,
    category: "specialises",
  },
  {
    id: "finance-7",
    title: "Crédit lombard",
    description: "Sur portefeuille titres",
    href: "/financements/credit-lombard",
    icon: Briefcase,
    category: "specialises",
  },
  // Crédits de restructuration
  {
    id: "finance-8",
    title: "Rachat de crédits",
    description: "Regroupement de prêts",
    href: "/financements/rachat-credits",
    icon: ArrowRightLeft,
    category: "restructuration",
  },
  {
    id: "finance-9",
    title: "Crédit hypothécaire",
    description: "Garanti par un bien immobilier",
    href: "/financements/credit-hypothecaire",
    icon: Building,
    category: "restructuration",
  },
  // Crédits spécifiques
  {
    id: "finance-10",
    title: "Prêt consommation",
    description: "Biens, travaux, projets",
    href: "/financements/pret-consommation",
    icon: Package,
    category: "specifiques",
  },
  {
    id: "finance-11",
    title: "Prêt viager hypothécaire",
    description: "Pour séniors, liquidité sans vente",
    href: "/financements/pret-viager",
    icon: Heart,
    category: "specifiques",
  },
  {
    id: "finance-12",
    title: "Vente à réméré",
    description: "Liquidité avec rachat possible",
    href: "/financements/vente-remere",
    icon: Receipt,
    category: "specifiques",
  },
];

// Assurances
export const assurances = [
  // Assurances Crédit & Santé
  {
    id: "assur-1",
    title: "Assurance emprunteur",
    description: "Protection crédit",
    href: "/assurances/emprunteur",
    icon: ShieldCheck,
    category: "credit-sante",
  },
  {
    id: "assur-2",
    title: "Complémentaire Santé",
    description: "Couverture santé optimale",
    href: "/assurances/complementaire-sante",
    icon: Heart,
    category: "credit-sante",
  },
  {
    id: "assur-3",
    title: "Complémentaire santé expatriés",
    description: "Santé internationale",
    href: "/assurances/sante-expatries",
    icon: Globe,
    category: "credit-sante",
  },
  {
    id: "assur-4",
    title: "Assurance voyage",
    description: "Protection voyage",
    href: "/assurances/voyage",
    icon: Plane,
    category: "credit-sante",
  },
  // Assurances Mobilité & Habitation
  {
    id: "assur-5",
    title: "Assurance habitation",
    description: "Protection du logement",
    href: "/assurances/habitation",
    icon: Home,
    category: "mobilite-habitation",
  },
  {
    id: "assur-6",
    title: "Assurance voiture",
    description: "Véhicule protégé",
    href: "/assurances/voiture",
    icon: Car,
    category: "mobilite-habitation",
  },
  {
    id: "assur-7",
    title: "Assurance deux-roues et quad",
    description: "Moto, scooter, quad",
    href: "/assurances/deux-roues",
    icon: Bike,
    category: "mobilite-habitation",
  },
  {
    id: "assur-8",
    title: "Assurance Bateaux / Jet-Skis",
    description: "Navigation protégée",
    href: "/assurances/bateaux",
    icon: Anchor,
    category: "mobilite-habitation",
  },
  // Assurances Décès & Prévoyance
  {
    id: "assur-9",
    title: "Assurance décès",
    description: "Capital ou rente",
    href: "/assurances/deces",
    icon: Users,
    category: "deces-prevoyance",
  },
  {
    id: "assur-10",
    title: "Assurance obsèques",
    description: "Frais funéraires",
    href: "/assurances/obseques",
    icon: Heart,
    category: "deces-prevoyance",
  },
  {
    id: "assur-11",
    title: "Garantie accident de la vie",
    description: "Protection complète",
    href: "/assurances/gav",
    icon: ShieldCheck,
    category: "deces-prevoyance",
  },
  // Assurances Immobilier
  {
    id: "assur-12",
    title: "Assurance PNO",
    description: "Propriétaire non occupant",
    href: "/assurances/pno",
    icon: Key,
    category: "immobilier",
  },
  {
    id: "assur-13",
    title: "Assurance PNO Immeuble",
    description: "Immeuble de rapport",
    href: "/assurances/pno-immeuble",
    icon: Building,
    category: "immobilier",
  },
  // Assurances Spécifiques
  {
    id: "assur-14",
    title: "Assurance études internationales",
    description: "Protection étudiants",
    href: "/assurances/etudes-internationales",
    icon: GraduationCap,
    category: "specifiques",
  },
];

// Gestion de fortune
export const gestionFortune = [
  // Services Exclusifs
  {
    id: "fortune-1",
    title: "Conseils multi-juridictionnel international",
    description: "Expertise cross-border",
    href: "/gestion-fortune/multi-juridictionnel",
    icon: Globe,
    category: "services-exclusifs",
  },
  {
    id: "fortune-2",
    title: "Family Office",
    description: "Gestion Multi-générationnelle",
    href: "/gestion-fortune/family-office",
    icon: Crown,
    category: "services-exclusifs",
  },
  {
    id: "fortune-3",
    title: "Gestion Discrétionnaire",
    description: "Délégation totale",
    href: "/gestion-fortune/gestion-discretionnaire",
    icon: Briefcase,
    category: "services-exclusifs",
  },
  {
    id: "fortune-4",
    title: "Optimisation Internationale",
    description: "Structuration globale",
    href: "/services/optimisation-internationale",
    icon: TrendingUp,
    category: "services-exclusifs",
  },
  {
    id: "fortune-5",
    title: "Immobilier de prestige",
    description: "Biens d'exception",
    href: "/gestion-fortune/immobilier-prestige",
    icon: Building2,
    category: "services-exclusifs",
  },
  {
    id: "fortune-6",
    title: "Gestion de fortune à 360°",
    description: "Un seul interlocuteur pour tout",
    href: "/gestion-fortune/360",
    icon: Star,
    category: "services-exclusifs",
  },
  // Produits Exclusifs
  {
    id: "fortune-7",
    title: "FIC (Fond interne collectif)",
    description: "Fond dédié collectif",
    href: "/gestion-fortune/fic",
    icon: Briefcase,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-8",
    title: "FAS (Fond assurance spécialisé)",
    description: "Solutions spécialisées",
    href: "/gestion-fortune/fas",
    icon: Shield,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-9",
    title: "FID (Fond interne dédié)",
    description: "Gestion personnalisée",
    href: "/gestion-fortune/fid",
    icon: Star,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-10",
    title: "Private Equity premium",
    description: "Opportunités exclusives",
    href: "/gestion-fortune/private-equity",
    icon: TrendingUp,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-11",
    title: "Hedge Funds",
    description: "Fonds alternatifs",
    href: "/gestion-fortune/hedge-funds",
    icon: LineChart,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-12",
    title: "Produits Structurés Tailor-Made",
    description: "Sur-mesure",
    href: "/gestion-fortune/structures",
    icon: Package,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-13",
    title: "Crédits Lombard",
    description: "Financement sur portefeuille",
    href: "/gestion-fortune/credit-lombard",
    icon: CreditCard,
    category: "produits-exclusifs",
  },
  {
    id: "fortune-14",
    title: "Crédit Hypothécaire Immobilier",
    description: "Financement premium",
    href: "/gestion-fortune/credit-hypothecaire",
    icon: Home,
    category: "produits-exclusifs",
  },
];

// Ressources
export const resources = [
  {
    id: "resource-1",
    title: "Webinaires",
    description: "Sessions live avec nos experts.",
    href: "/ressources/webinaires",
    icon: Calendar,
  },
  {
    id: "resource-2",
    title: "Guides fiscaux",
    description: "Guides pratiques téléchargeables.",
    href: "/ressources/guides",
    icon: Book,
  },
  {
    id: "resource-3",
    title: "Actualités",
    description: "Dernières actualités fiscales.",
    href: "/blog",
    icon: Newspaper,
  },
  {
    id: "resource-4",
    title: "Vidéos",
    description: "Tutoriels et cas pratiques.",
    href: "/ressources/videos",
    icon: PlayCircle,
  },
  {
    id: "resource-5",
    title: "Simulateurs",
    description: "Calculez vos économies d'impôts.",
    href: "/ressources/simulateurs",
    icon: Calculator,
  },
  {
    id: "resource-6",
    title: "FAQ",
    description: "Réponses à vos questions.",
    href: "/ressources/faq",
    icon: Search,
  },
  {
    id: "resource-7",
    title: "Témoignages",
    description: "Retours d'expérience clients.",
    href: "/ressources/temoignages",
    icon: Heart,
  },
];

// Simulateurs
export const simulateurs = [
  {
    id: "sim-1",
    title: "Calculatrice intérêts composés",
    description: "Calculez la croissance de vos investissements",
    href: "/ressources/simulateurs/calculatrice-interets-composes",
    icon: Calculator,
  },
];

// Rendez-vous
export const rendezVous = [
  {
    id: "rv-1",
    title: "Bilan Patrimonial 360°",
    description: "Analyse complète de votre situation",
    href: "/bilan-patrimonial",
    icon: PieChart,
    badge: { text: "Gratuit", color: "green" },
  },
  {
    id: "rv-2",
    title: "Consultation Elite",
    description: "Conseil personnalisé haut de gamme",
    href: "/consultation-elite",
    icon: Crown,
    badge: { text: "VIP - Gratuit", color: "gold" },
  },
  {
    id: "rv-3",
    title: "Stratégie 1h",
    description: "Session de travail d'1 heure",
    href: "/strategie-1h",
    icon: Lightbulb,
    badge: { text: "149€/h", color: "blue" },
  },
  {
    id: "rv-4",
    title: "Stratégies 2h",
    description: "Session approfondie de 2 heures",
    href: "/strategie-2h",
    icon: Target,
    badge: { text: "269€/2h", color: "blue" },
  },
  {
    id: "rv-5",
    title: "Hagnéré Investissement",
    description: "Découvrez nos opportunités exclusives",
    href: "/presentation-investissement",
    icon: Briefcase,
    badge: { text: "Gratuit", color: "green" },
  },
];
