#!/bin/bash

echo "🔧 Configuration du fichier .env.local"
echo "====================================="
echo ""
echo "Copier et coller ces lignes dans votre fichier .env.local :"
echo ""
echo "# Database Configuration"
echo "DATABASE_URL=\"postgresql://postgres:password@localhost:5432/hagnere_patrimoine?schema=public\""
echo ""
echo "# NextAuth Configuration"
echo "NEXTAUTH_URL=http://localhost:3000"
echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo ""
echo "# AWS S3 Configuration (conserver vos valeurs existantes)"
echo "AWS_REGION=eu-north-1"
echo "AWS_ACCESS_KEY_ID=AKIA2NX46MXORQJECK4I"
echo "AWS_SECRET_ACCESS_KEY=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"
echo "AWS_BUCKET_NAME=hagnerepatrimoine"
echo ""
echo "# Synchronisation articles"
echo "INVESTISSEMENT_API_BASE=https://hagnere-investissement.fr"
echo "INVESTISSEMENT_SYNC_SECRET=integration-sync-secret"
echo "PATRIMOINE_BASE_URL=http://localhost:3000"
echo "PATRIMOINE_SYNC_SECRET=integration-sync-secret"
echo ""
echo "====================================="
echo "📝 Instructions :"
echo "1. Ouvrez .env.local dans votre éditeur"
echo "2. Remplacez tout le contenu par les lignes ci-dessus"
echo "3. Sauvegardez le fichier"
echo "4. Relancez le serveur avec : npm run dev"
